# Inserts a blank line between shell prompts
add_newline = false

# Change the format
format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$memory_usage\
$battery\
$time\
$status\
$python\
$shell\
$character"""

[username]
show_always = true


[line_break]
disabled = true
